##### Libraries and data clean up

In [2]:
import pandas as pd
import ast
df = pd.read_csv('data.csv')

#Turn Artists into two seperate artist
df['artists'] = df['artists'].apply(ast.literal_eval)

# One row per artist
df = df.explode('artists')

##### Taylor Swift

In [3]:
tswift = df[df['artists'].str.lower() == 'taylor swift'].reset_index(drop = True)
tswift.head()

,id,name,artists,duration_ms,release_date,year,acousticness,danceability,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,mode,key,popularity,explicit
0,4XrP7vKBjKLEYlRZdb0Ygr,Tell Me Why,Taylor Swift,200560,11/11/08,2008,0.0606,0.601,0.852,0.000003,0.370,-3.096,0.0386,100.015,0.513,1,7,44,0
1,6XDBA3QWX51lDJ0oZbaJJN,Long Live,Taylor Swift,317947,10/25/10,2010,0.0360,0.418,0.680,0.000076,0.108,-4.300,0.0346,204.125,0.142,1,7,47,0
2,3kfgJql90tzgoxByioAMXR,Innocent,Taylor Swift,302253,10/25/10,2010,0.1860,0.552,0.608,0.000000,0.125,-5.290,0.0259,134.050,0.170,0,1,47,0
3,7hZuICN5eaCuQyp443RCt6,Dear John,Taylor Swift,403920,10/25/10,2010,0.1660,0.589,0.470,0.000001,0.112,-5.320,0.0280,119.386,0.102,1,4,46,0
4,2R7C9dDqv1UPycvepBFziA,Superman,Taylor Swift,275960,10/25/10,2010,0.0268,0.582,0.765,0.000002,0.103,-3.648,0.0324,131.982,0.559,1,7,46,0

##### Drake

In [4]:
drake = df[df['artists'].str.lower() == 'drake'].reset_index(drop = True)
drake.head()

,id,name,artists,duration_ms,release_date,year,acousticness,danceability,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,mode,key,popularity,explicit
0,2TWSilrWcTrgVKcP8kfEfg,Unstoppable (feat. Santigold & Lil Wayne),Drake,209957,2009,2009,0.16500,0.774,0.912,0.000000,0.7450,-2.787,0.347,150.083,0.821,0,2,48,1
1,6MlGqWzDiLkZ0vmAEsisEk,The Calm,Drake,243724,2009,2009,0.81900,0.471,0.784,0.000011,0.1070,-8.250,0.883,160.833,0.258,0,11,48,1
2,5bDEA48Dxyxoc3K4Dt7yRE,Karaoke,Drake,227960,1/1/10,2010,0.00879,0.758,0.654,0.025800,0.0797,-7.097,0.116,151.008,0.949,1,0,46,0
3,32BNHfgpllA7lHnALwD3bE,Moment 4 Life,Drake,279307,11/22/10,2010,0.40900,0.475,0.882,0.000000,0.2430,-3.883,0.351,98.000,0.369,1,11,50,1
4,5o5KX1f1JBQ2SxGzE8RQQA,It's Good,Drake,241467,1/1/11,2011,0.02440,0.666,0.715,0.000000,0.1190,-7.292,0.156,85.356,0.100,1,8,47,1

##### Harry Styles

In [5]:
hstyles = df[df['artists'].str.lower() == 'harry styles'].reset_index(drop = True)
hstyles.head()

,id,name,artists,duration_ms,release_date,year,acousticness,danceability,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,mode,key,popularity,explicit
0,5Ohxk2dO5COHF1krpoPigN,Sign of the Times,Harry Styles,340707,5/12/17,2017,0.0275,0.516,0.595,0.000000,0.109,-4.630,0.0313,119.972,0.2220,1,5,81,0
1,6UelLqGlWMcVH1E5c4H7lY,Watermelon Sugar,Harry Styles,174000,12/13/19,2019,0.1220,0.548,0.816,0.000000,0.335,-4.209,0.0465,95.390,0.5570,1,0,90,0
2,3jjujdWJ72nww5eGnfs2E7,Adore You,Harry Styles,207133,12/13/19,2019,0.0237,0.676,0.771,0.000007,0.102,-3.675,0.0483,99.048,0.5690,1,8,88,0
3,1ZMiCix7XSAbfAJlEZWMCp,Falling,Harry Styles,240133,12/13/19,2019,0.8390,0.567,0.267,0.000001,0.089,-6.502,0.0299,110.011,0.0592,1,4,87,0
4,1M4qEo4HE3PRaCOM7EXNJq,Adore You,Harry Styles,207133,12/6/19,2019,0.0237,0.676,0.771,0.000007,0.102,-3.675,0.0483,99.048,0.5690,1,8,86,0

#####  Michael Jackson

In [6]:
jackson = df[df['artists'].str.lower() == 'michael jackson'].reset_index(drop = True)
jackson.head()

,id,name,artists,duration_ms,release_date,year,acousticness,danceability,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,mode,key,popularity,explicit
0,1jrJQ1Gib2ubaxAXe1z2Jc,You've Got A Friend,Michael Jackson,298960,1/24/72,1972,0.5010,0.543,0.635,0.000001,0.0955,-8.967,0.0351,168.399,0.810,1,0,27,0
1,0QBDsZH9PDnKVQBxEcefku,Music And Me,Michael Jackson,162520,8/13/73,1973,0.7310,0.352,0.276,0.000143,0.1440,-11.737,0.0274,148.518,0.219,1,4,29,0
2,0FsyTSZ4Ghi1SpKJvJfJnZ,Billie Jean (Home Demo from 1981),Michael Jackson,140040,11/30/82,1982,0.0681,0.953,0.441,0.000111,0.0635,-8.462,0.0434,114.979,0.520,0,6,38,0
3,4DdtaYlJk11wRpRC6eMhHa,Don't Be Messin' 'Round,Michael Jackson,259480,8/31/87,1987,0.0568,0.931,0.737,0.015500,0.0431,-7.975,0.0443,120.929,0.973,1,11,41,0
4,0oleopAuBlxuq7fcFl9Ap8,Fly Away,Michael Jackson,207080,8/31/87,1987,0.1020,0.763,0.564,0.000000,0.0415,-7.630,0.0293,110.906,0.525,1,8,39,0

##### Kanye West

In [7]:
kanye = df[df['artists'].str.lower() == 'kanye west'].reset_index(drop = True)
kanye.head()

,id,name,artists,duration_ms,release_date,year,acousticness,danceability,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,mode,key,popularity,explicit
0,4BhwlQ9mTwhFGXpQvP9JTV,Lil Jimmy Skit,Kanye West,53640,2/10/04,2004,0.8030,0.640,0.279,0.00000,0.375,-12.396,0.484,82.475,0.741,1,10,46,1
1,164al00XRSLWG6h4hc12bD,Skit #1,Kanye West,33573,9/30/05,2005,0.4670,0.799,0.307,0.00000,0.146,-12.543,0.917,52.165,0.753,1,1,46,1
2,7r6PigmGzlB3YPB7wvBBbi,No Church In The Wild,Kanye West,272507,8/8/11,2011,0.2440,0.654,0.750,0.01780,0.167,-7.509,0.105,92.773,0.557,0,8,55,1
3,5zes2uxTNuqNlO6toDTZN5,Primetime,Kanye West,199240,8/8/11,2011,0.1660,0.662,0.923,0.00001,0.310,-4.085,0.210,84.990,0.469,0,11,51,1
4,7eW9cHOAHmYqphs5tWXETw,Clique,Kanye West,293613,1/1/12,2012,0.0601,0.710,0.555,0.00000,0.227,-5.942,0.295,109.204,0.303,0,9,49,1

##### Tame Impala

In [8]:
tame = df[df['artists'].str.lower() == 'tame impala'].reset_index(drop = True)
tame.head()

,id,name,artists,duration_ms,release_date,year,acousticness,danceability,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,mode,key,popularity,explicit
0,5VdLK7Kcqyf5RstFU0lhwh,Skeleton Tiger,Tame Impala,264800,1/1/08,2008,0.7290,0.611,0.679,0.481000,0.1670,-6.996,0.0397,121.962,0.495,1,2,45,0
1,4m3GHOgCNZMv0we7H9j8Y8,Expectation,Tame Impala,362880,5/21/10,2010,0.0222,0.450,0.849,0.004550,0.0792,-5.075,0.0570,139.925,0.161,1,5,48,0
2,3Naa5mKj5pbrNGyHsE04zo,The Less I Know The Better,Tame Impala,218200,6/12/20,2020,0.0106,0.622,0.784,0.008900,0.1040,-3.830,0.0292,116.892,0.780,0,1,0,1
3,558ubozatFQlweufvHa3Ip,It Might Be Time,Tame Impala,273027,2/14/20,2020,0.0210,0.585,0.781,0.000187,0.6270,-3.808,0.0457,115.946,0.336,1,2,68,0
4,4Bj7sPp72rZs5xZb8Z1RtP,I Don't Really Mind,Tame Impala,225893,5/21/10,2010,0.5760,0.455,0.842,0.023600,0.1600,-5.996,0.0867,136.958,0.270,1,11,47,0

##### Bruno Mars

In [9]:
bruno = df[df['artists'].str.lower() == 'bruno mars'].reset_index(drop = True)
bruno.head()

,id,name,artists,duration_ms,release_date,year,acousticness,danceability,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,mode,key,popularity,explicit
0,7Cj2tT0m2SBeIO1PsGfk8A,Grenade - Acoustic,Bruno Mars,249535,2/8/11,2011,0.8180,0.643,0.394,0.000000,0.0888,-6.305,0.0305,97.911,0.364,0,2,60,0
1,4REEbsJ6WV9NoGubnlhnkm,Bubble Butt,Bruno Mars,227813,4/16/13,2013,0.0115,0.765,0.771,0.002370,0.6060,-6.990,0.3470,194.072,0.394,1,7,51,0
2,0B0tYbVp7pDQAqKDhgMeaL,Too Good to Say Goodbye,Bruno Mars,281827,11/17/16,2016,0.0389,0.587,0.630,0.000000,0.3500,-6.054,0.0311,76.970,0.433,1,2,65,0
3,6ObpR8ek44tvWefQRcSo8K,Calling All My Lovelies,Bruno Mars,250080,11/17/16,2016,0.0392,0.662,0.705,0.000002,0.1050,-6.560,0.0399,159.996,0.865,0,1,63,0
4,1GDrGx9VWaAgaekuddnLYq,Treasure,Bruno Mars,176093,12/10/12,2012,0.0291,0.872,0.699,0.000121,0.0639,-5.071,0.0349,116.033,0.934,0,5,48,0

##### Katy Perry

In [10]:
kperry = df[df['artists'].str.lower() == 'katy perry'].reset_index(drop = True)
kperry.head()

,id,name,artists,duration_ms,release_date,year,acousticness,danceability,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,mode,key,popularity,explicit
0,4pHiSrrtHFlXH3DYACegi0,Hot N Cold,Katy Perry,220227,6/17/08,2008,0.000079,0.706,0.841,0.000000,0.0688,-3.956,0.0418,132.032,0.861,1,7,44,0
1,5NFiJqwS8iMtJwGOgTKa2v,I Kissed A Girl,Katy Perry,179640,6/17/08,2008,0.002230,0.699,0.760,0.000000,0.1320,-3.173,0.0677,129.996,0.696,1,5,44,0
2,4NmE2ytXI8S2svTRSmEdpO,Small Talk,Katy Perry,161963,8/9/19,2019,0.203000,0.846,0.631,0.000000,0.4550,-5.547,0.1000,115.999,0.602,1,5,74,0
3,22Lg6vvMS2JC07aAjsGvtU,Hot N Cold,Katy Perry,223227,9/9/08,2008,0.000081,0.702,0.839,0.000000,0.0720,-3.992,0.0439,132.007,0.856,1,7,52,0
4,5nCthAh3jt4xKuLJAifAaR,Harleys In Hawaii,Katy Perry,185815,10/16/19,2019,0.185000,0.722,0.757,0.000006,0.1260,-6.207,0.1320,140.094,0.721,0,10,73,0

##### Morgan Wallen

In [11]:
morgan = df[df['artists'].str.lower() == 'morgan wallen'].reset_index(drop = True)
morgan.head()

,id,name,artists,duration_ms,release_date,year,acousticness,danceability,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,mode,key,popularity,explicit
0,5x7Fb9wMOtxd7eZzQ9EzVd,Gone Girl,Morgan Wallen,163453,4/27/18,2018,0.28700,0.527,0.868,0.000000,0.0885,-2.653,0.0416,172.086,0.770,1,2,61,0
1,7N3MO5mFhgoH2VRvydLxsJ,If I Ever Get You Back,Morgan Wallen,173960,4/27/18,2018,0.01380,0.673,0.876,0.000000,0.2110,-3.338,0.0345,139.951,0.962,1,0,60,0
2,65IHmBagtQrYRcJd8a47zv,He Went To Jared (HARDY feat. Morgan Wallen),Morgan Wallen,213693,9/13/19,2019,0.05400,0.563,0.806,0.000008,0.2040,-5.110,0.0474,140.075,0.680,0,9,61,0
3,0j7uEVfgFV1UmUoXml6dXX,Collide - The Voice Performance,Morgan Wallen,221485,1/1/14,2014,0.06360,0.487,0.760,0.000000,0.1160,-5.633,0.0268,93.991,0.245,1,0,47,0
4,1yj1ZztSGITJ5Nf4mfH92c,Spin You Around,Morgan Wallen,212850,8/24/15,2015,0.00147,0.517,0.877,0.000000,0.2080,-3.621,0.0297,150.004,0.616,1,4,67,0

##### Bad Bunny

In [12]:
bunny = df[df['artists'].str.lower() == 'bad bunny'].reset_index(drop = True)
bunny.head()

,id,name,artists,duration_ms,release_date,year,acousticness,danceability,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,mode,key,popularity,explicit
0,2QrGCbW0ylj94JfkgLZFlA,Pa Ti,Bad Bunny,191295,1/2/17,2017,0.3480,0.760,0.718,0.000000,0.0982,-3.017,0.2320,128.140,0.557,1,1,67,1
1,5YY7ht3PCArlLjLbcTiAvh,"Escápate Conmigo (feat. Ozuna, Bad Bunny, De L...",Bad Bunny,386333,12/1/17,2017,0.0464,0.797,0.804,0.000015,0.3170,-4.817,0.0711,91.973,0.451,1,1,67,0
2,2wRkBumdItthjYP9XknImg,Está Rico,Bad Bunny,215151,9/28/18,2018,0.2660,0.817,0.740,0.000000,0.0992,-4.566,0.2830,130.040,0.674,0,11,69,0
3,0r9d60ZYPAlFHq8qnUtkXN,Madura (feat. Bad Bunny),Bad Bunny,190909,4/13/18,2018,0.1380,0.878,0.555,0.000001,0.1510,-7.639,0.2020,88.029,0.751,0,1,70,0
4,71pEiUWwfDFiRO6RmFpnBf,MOJAITA,Bad Bunny,187333,6/28/19,2019,0.0171,0.450,0.842,0.000000,0.3770,-3.602,0.1020,172.069,0.885,1,0,72,0

In [13]:
df = pd.concat([kanye, drake, bunny, bruno, kperry, tswift, hstyles, morgan, tame, jackson], axis = 0).reset_index(drop=True)

df = df[df['duration_ms'] > 53000]
df['duration_ms'] = df['duration_ms']/1000

df = df.rename(columns = {'duration_ms' : 'duration_s'})

df['Year_dt'] = pd.to_datetime(df['year'], format='%Y')

##### Save to a CSV

In [14]:
df.to_csv('app_artists.csv')